### ISSUE TITLE
Safari cannot open the file

### ISSUE THREAD

**Issue by karthick-manoharan** [nwcell/ics.js#13] opened 2014-08-21 06:31 UTC
On running the demo page in iPhone 5s iOS 7.1.1 new tab opens for a litle time later "Safari can't open the file" shows. 

Where as in iPhone 5 iOS 7.0.1 new tab opens nothing no activity is noticed.

**Comment by tburdeinei** [comment] 2015-04-18 02:51
+1

**Comment by nwcell** [comment] 2017-09-14 20:17
Duplicate of: https://github.com/nwcell/ics.js/issues/27

**Closed by nwcell** 2017-09-14 20:17 UTC
Labels: duplicate
